-- MySQL Script generated by MySQL Workbench
-- Wed Apr 26 18:02:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `first_lastname` VARCHAR(45) NOT NULL,
  `second_lastname` VARCHAR(45) NOT NULL,
  `age` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`event` (
  `title` VARCHAR(45) NOT NULL,
  `date_event` DATE NOT NULL,
  `hour_event` TIME NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`title`),
  INDEX `fk_event_user1_idx` (`user_email` ASC) VISIBLE,
  CONSTRAINT `fk_event_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `longitude` VARCHAR(45) NOT NULL,
  `latitude` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  `event_title` VARCHAR(45) NOT NULL,
  INDEX `fk_table1_user_idx` (`user_email` ASC) VISIBLE,
  PRIMARY KEY (`user_email`),
  INDEX `fk_location_event1_idx` (`event_title` ASC) VISIBLE,
  CONSTRAINT `fk_table1_user`
    FOREIGN KEY (`user_email`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_location_event1`
    FOREIGN KEY (`event_title`)
    REFERENCES `mydb`.`event` (`title`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`post` (
  `date_post` DATE NOT NULL,
  `hour_post` TIME NOT NULL,
  `OS` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `text` VARCHAR(45) NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`date_post`, `hour_post`, `user_email`),
  INDEX `fk_table1_user1_idx` (`user_email` ASC) VISIBLE,
  CONSTRAINT `fk_table1_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `text` VARCHAR(45) NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  `post_date_post` DATE NOT NULL,
  `post_hour_post` TIME NOT NULL,
  `post_user_email` VARCHAR(45) NOT NULL,
  INDEX `fk_comment_user1_idx` (`user_email` ASC) VISIBLE,
  INDEX `fk_comment_post1_idx` (`post_date_post` ASC, `post_hour_post` ASC, `post_user_email` ASC) VISIBLE,
  PRIMARY KEY (`post_user_email`, `post_hour_post`, `post_date_post`),
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_post1`
    FOREIGN KEY (`post_date_post` , `post_hour_post` , `post_user_email`)
    REFERENCES `mydb`.`post` (`date_post` , `hour_post` , `user_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`likes` (
  `date_likes` DATE NOT NULL,
  `hour_likes` TIME NOT NULL,
  `likescol` VARCHAR(45) NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  `post_date_post` DATE NOT NULL,
  `post_hour_post` TIME NOT NULL,
  `post_user_email` VARCHAR(45) NOT NULL,
  INDEX `fk_likes_post1_idx` (`post_date_post` ASC, `post_hour_post` ASC, `post_user_email` ASC) VISIBLE,
  PRIMARY KEY (`post_user_email`, `post_hour_post`, `post_date_post`),
  CONSTRAINT `fk_likes_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_post1`
    FOREIGN KEY (`post_date_post` , `post_hour_post` , `post_user_email`)
    REFERENCES `mydb`.`post` (`date_post` , `hour_post` , `user_email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pages` (
  `url` VARCHAR(45) NOT NULL,
  `date_page` DATE NOT NULL,
  `hour_page` TIME NOT NULL,
  `name_page` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`url`),
  INDEX `fk_pages_user1_idx` (`user_email` ASC) VISIBLE,
  CONSTRAINT `fk_pages_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ads`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ads` (
  `text_add` VARCHAR(45) NOT NULL,
  `expiry` VARCHAR(45) NOT NULL,
  `date_ad` DATE NOT NULL,
  `hour_add` TIME NOT NULL,
  `pages_url` VARCHAR(45) NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`date_ad`, `hour_add`, `pages_url`),
  INDEX `fk_ads_pages1_idx` (`pages_url` ASC) VISIBLE,
  INDEX `fk_ads_user1_idx` (`user_email` ASC) VISIBLE,
  CONSTRAINT `fk_ads_pages1`
    FOREIGN KEY (`pages_url`)
    REFERENCES `mydb`.`pages` (`url`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ads_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clicks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clicks` (
  `date_click` DATETIME NOT NULL,
  `hour_click` TIME NOT NULL,
  `ads_date_ad` DATE NOT NULL,
  `ads_hour_add` TIME NOT NULL,
  `ads_pages_url` VARCHAR(45) NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ads_date_ad`, `ads_hour_add`, `ads_pages_url`),
  INDEX `fk_clicks_ads1_idx` (`ads_date_ad` ASC, `ads_hour_add` ASC, `ads_pages_url` ASC) VISIBLE,
  INDEX `fk_clicks_user1_idx` (`user_email` ASC) VISIBLE,
  CONSTRAINT `fk_clicks_ads1`
    FOREIGN KEY (`ads_date_ad` , `ads_hour_add` , `ads_pages_url`)
    REFERENCES `mydb`.`ads` (`date_ad` , `hour_add` , `pages_url`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clicks_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`message` (
  `text_message` VARCHAR(45) NOT NULL,
  `hour_message` TIME NOT NULL,
  `date_message` TIME NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  `email_receive` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`hour_message`, `date_message`, `user_email`),
  INDEX `fk_message_user1_idx` (`user_email` ASC) VISIBLE,
  CONSTRAINT `fk_message_user1`
    FOREIGN KEY (`user_email`)
    REFERENCES `mydb`.`user` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


--consultas--

--P3.1--
SELECT *
FROM user

--P3.2--

SELECT count(address), address
from location, user
WHERE email=user_email
GROUP BY address
ORDER BY count(address) desc
limit 1

--p3.3--


SELECT post_user_email
FROM comment, post
WHERE comment.post_user_email=post.user_email

select likes.user_email
from likes, post
where  likes.user_email in
       (SELECT post_user_email
        FROM comment, post
        WHERE comment.post_user_email=post.user_email
        )


SELECT user.*
FROM user
WHERE user.email= (select likes.user_email
from likes
where likes.post_user_email in (SELECT post_user_email
FROM comment, post
WHERE comment.post_user_email=post.user_email
)
group by likes.user_email
order by count((likes.user_email)) desc
limit 1)

--p5--

SELECT count(pages_url)
FROM ads
WHERE pages_url="https://ulink.cl/beauchef"

SELECT count(clicks.user_email) as num_clicks
FROM clicks, ads
WHERE date_ad=ads_date_ad
AND ads_hour_add=hour_add AND clicks.ads_pages_url = "https://ulink.cl/beauchef"
GROUP BY date_ad, hour_add





SELECT count(num_clicks)
FROM (SELECT count(clicks.user_email) as num_clicks
FROM clicks, ads
WHERE date_ad=ads_date_ad
AND ads_hour_add=hour_add AND clicks.ads_pages_url = "https://ulink.cl/beauchef"
GROUP BY date_ad, hour_add) AS t
WHERE num_clicks >=2



--P3.5--
SELECT (SELECT count(num_clicks)
FROM (SELECT count(clicks.user_email) as num_clicks
FROM clicks, ads
WHERE date_ad=ads_date_ad
AND ads_hour_add=hour_add AND clicks.ads_pages_url = "https://ulink.cl/beauchef"
GROUP BY date_ad, hour_add) AS t
WHERE num_clicks >=2
)/(SELECT count(pages_url)
FROM ads
WHERE pages_url="https://ulink.cl/beauchef")*100


--p6----

SELECT name_page
from pages
where url =(SELECT pages_url
FROM clicks, ads
WHERE date_ad=ads_date_ad
AND ads_hour_add=hour_add
GROUP BY date_ad, hour_add,pages_url
ORDER BY count(ads.user_email) desc
limit 1)

--p7---

SELECT count(type)
FROM post
WHERE type=3


select sum(likes)
from (SELECT count(likes.user_email) as likes
FROM post, likes
WHERE type=3 AND post.user_email=likes.post_user_email
GROUP BY likes.post_user_email) as t

SELECT (select sum(likes)
from (SELECT count(likes.user_email) as likes
FROM post, likes
WHERE type=3 AND post.user_email=likes.post_user_email
GROUP BY likes.post_user_email) as t)/(
SELECT count(type)
FROM post
WHERE type=3)*100


--p8--

SELECT count(message.user_email)
FROM message, user
WHERE
    message.text_message="soy industrial" and
    user.gender="h" and message.user_email=user.email






